track_parcel:
  fields:
    tracking_code:
      required: true
      example: "1234567890123456"
      selector:
        text:

untrack_parcel:
  fields:
    tracking_code:
      required: true
      example: "1234567890123456"
      selector:
        text:
